### ISSUE TITLE
Issue on your board

### ISSUE THREAD

**Issue by xiaofen9** [MenchiG/DJI-Onboard-SDK-Raspberry-Transparent-Transmit#7]
Hello, thank you for your detailed doc for DJi & Raspberry 
But I am wondering how do you support your Raspberry's energy on the air? Are u using a portable power?
And which system do you install for your Raspberry? ubuntu?

**Comment by MenchiG** [comment]
The power is provided by M100's battery.
The system of Raspberry is the original one, Raspbian.

**Comment by xiaofen9** [comment]
Thank you! you are so nice~
