### ISSUE TITLE
DJI Onboard SDK (use Library tensorflow or other library)

### ISSUE THREAD

**Issue by ZIKO94ZIKO** [MenchiG/DJI-Onboard-SDK-Raspberry-Transparent-Transmit#9]
Hi MenchiG 
I hope you are doing well , i have a question please  : have you tried live stream or shooting video  and scan the object like ( faces, cars, aniamals) by library  Tensorflow or other Library , please send me the scripts if you have it.
best regards

**Comment by MenchiG** [comment]
Sorry, I did not try it. Actually, I am not sure whether DJI-Onboard-Transparent-Transmit is able to handle live stream video.
